name: PlatformIO Dependabot

on:
  workflow_dispatch:
  schedule:
    # Runs every day at 00:00
    - cron: '0 4 * * *'
   

permissions:
  contents: write
  pull-requests: write 

 
jobs:
  dependabot:
    runs-on: ubuntu-latest
    name: run PlatformIO Dependabot
    
    defaults:
      run:
        working-directory: arduino
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run PlatformIO Dependabot
        uses: peterus/platformio_dependabot@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
